Document: artisan-aliases
Title: Debian artisan-aliases Manual
Author: <insert document author here>
Abstract: This manual describes what artisan-aliases is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/artisan-aliases/artisan-aliases.sgml.gz

Format: postscript
Files: /usr/share/doc/artisan-aliases/artisan-aliases.ps.gz

Format: text
Files: /usr/share/doc/artisan-aliases/artisan-aliases.text.gz

Format: HTML
Index: /usr/share/doc/artisan-aliases/html/index.html
Files: /usr/share/doc/artisan-aliases/html/*.html
